name: '@tommartinezjr'
favicon: null
layout_spectrum: 0.2417
typography_spectrum: 0.34556
title: 'The Portfolio of Visual Media Artist, Tom Martinez Jr.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8eb9e5'
    - '#ffffff'
    - '#2d2b30'
    - '#c08160'
    - '#c73b8d'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
