name: '@tommartinezjr'
favicon: null
layout_spectrum: 0.93626
typography_spectrum: 0.34556
title: 'The Portfolio of Visual Media Artist, Tom Martinez Jr.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefe'
    - '#676a8e'
    - '#6033fc'
    - '#c8c8dd'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
